services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: pets:latest
    container_name: pets
    ports: 
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JAVA_OPTS=${JAVA_OPTS:-Xmx512m} 
    depends_on:
      db:
        condition: service_healthy 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  db:
    image: postgres:17-alpine
    container_name: pets_app_db
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-user}"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  db_data:
  

