spring:
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    drop-first: false
    enabled: true
    default-schema: public 
  datasource:
    url: SPRING_DATASOURCE_URL=${DATASOURCE_URL}
    username: SPRING_DATASOURCE_USERNAME=${DB_USER}
    password: SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none 
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    lazy-initialization: true
  data:
    redis:
      database: 0
      password: ${SPRING_REDIS_PASSWORD:}
      timeout: 2000ms
      port: 6379
      host: ${SPRING_REDIS_HOST}
server:
  port: 8088 

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    redis.clients.jedis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"


